### ISSUE TITLE
Bug in superabundant -> partitions_of_n function 

### ISSUE THREAD

**Issue by alexsanjoseph** [j2kun/riemann-divisor-sum#39]
I was trying to reproduce the blog post and the code here and I think I have run into a bug.

`partitions_of_n` function gives the wrong partitions where n > 5. For example, 

`partitions_of_n(6)` currently gives

```
list(enumerate([[6], [5, 1], [4, 2], [4, 1, 1],
        [3,3, 1], [3, 2, 1], [3,1,1,1],
         [2,2,2, 1], [2, 2, 1, 1], [2, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]))
```

but it should be giving

```
list(enumerate([[6], [5, 1], [4, 2], [4, 1, 1],
        [3,3], [3, 2, 1], [3,1,1,1],
         [2,2,2], [2, 2, 1, 1], [2, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]])),
```

**[3,3,1] and [2,2,2,1] instead of [3,3] and [2,2,2]**

the `partitions_of_n` function works correctly till n = 5 and always gives the right number of partition count so the tests fail to capture this.

**Comment by j2kun** [comment]
🤯 I thought I had tested that pretty well... Let me take a look

**Comment by alexsanjoseph** [comment]
Ironically, Just learned about property testing from your post, which comes immediately after this. I think if you had a test which checked if sum of each  partition added to the number itself, you'd have caught it. 🤦🏾‍♂️

**Comment by j2kun** [comment]
We're thinking the same thing :)

Admittedly, I could have documented this algorithm a lot better than I did.

If you're interested, you can take a look at https://github.com/j2kun/riemann-divisor-sum/pull/40. Not asking for a detailed review, only if you're interested.

**Comment by j2kun** [comment]
Thanks for the bug report! I hope you have as much fun with the rest of your blog post series is as I did with mine :)

**Comment by alexsanjoseph** [comment]
Your PR looks good, thanks. 

Honestly, I didn't understand the algorithm implementation completely, so couldn't suggest a fix myself. In my post I'm using a memoized recursive approach (is this dynamic programming?) which my brain can comprehend - albeit being slightly slower than your function. 

If you have the time, please take a look at 

- https://github.com/alexsanjoseph/riemann-divisor-sum-go/blob/search_strategies/riemann/superabundant.go
- https://github.com/alexsanjoseph/riemann-divisor-sum-go/blob/search_strategies/riemann/superabundant_test.go

. I will be adding property tests soon :)
